# For local purposes. Use Command docker compose up --build
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: systematicdefence-app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/app
      - ./routes:/var/www/html/routes
      - ./resources:/var/www/html/resources
      - ./public:/var/www/html/public
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: systematicdefence
      DB_USERNAME: root
      DB_PASSWORD: root
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: systematicdefence-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: systematicdefence
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: system-developer
      PMA_PASSWORD: yourpassword

volumes:
  dbdata:
